<?php
declare(strict_types=1); require __DIR__ . '/config.php';
$pageTitle = 'About Visa Hat | Visa Hat';
$metaDescription = 'Who Visa Hat is, how the consultancy works, and the principles behind its guidance.';
require __DIR__ . '/includes/header.php';
?>
<main id="main-content">
<section class="page-hero about-hero"><div class="container"><p class="breadcrumb"><a href="/">Home</a><span>/</span>About</p><p class="eyebrow">About Visa Hat</p><h1>An independent place to <strong>prepare, not just apply.</strong></h1><p class="lede">Visa Hat is a visa and immigration consultation service. We help people organise their questions and understand preparation before they commit to a path — we do not process or submit applications on anyone's behalf.</p></div></section>

<section class="section identity-section"><div class="container identity-layout"><div class="identity-art" aria-hidden="true"><svg viewBox="0 0 220 200"><circle cx="88" cy="96" r="58" fill="none" stroke="#0867e8" stroke-width="3"/><circle cx="88" cy="96" r="6" fill="#0867e8"/><path d="M88 96 32 60" stroke="#0867e8" stroke-width="3" stroke-linecap="round"/><path d="M96 60c34 10 62 40 78 84" fill="none" stroke="#149d98" stroke-width="3" stroke-dasharray="1 9" stroke-linecap="round"/><path d="M168 132c9 3 17 10 20 20-11 1-20-3-27-10Z" fill="#ef7182"/><circle cx="150" cy="34" r="10" fill="#efa833"/></svg></div><div class="identity-copy"><h2>An independent starting point</h2><p>Visa applications involve a lot of scattered information spread across official guidance, forums, and word of mouth. Visa Hat exists to turn that into one focused conversation, so you leave with a clearer, more realistic view of your options.</p><dl class="identity-pillars"><div><dt>Approach</dt><dd>We start from your circumstances rather than a fixed script — a consultation adapts to your destination, timeline, and the questions you already have.</dd></div><div><dt>Honesty</dt><dd>We do not promise outcomes. Immigration decisions depend on rules and personal circumstances outside our control, and we say so plainly.</dd></div></dl></div></div></section>

<section class="section approach-section"><div class="container"><header class="section-heading left-heading"><p class="eyebrow">How we work with you</p><h2>From a first conversation to a clearer next step.</h2></header><ol class="approach-timeline"><li><span class="stage">1</span><div class="stage-copy"><h3>You share your context</h3><p>Your destination, purpose, and roughly where you are in your planning.</p></div></li><li><span class="stage">2</span><div class="stage-copy"><h3>We talk it through</h3><p>A consultant discusses your situation and answers the questions you bring.</p></div></li><li><span class="stage">3</span><div class="stage-copy"><h3>You get a clearer view</h3><p>You leave with a more practical understanding of what to prepare next.</p></div></li><li><span class="stage">4</span><div class="stage-copy"><h3>You return if needed</h3><p>Follow-up conversations are available as your plan develops.</p></div></li></ol></div></section>

<section class="section principles-section"><div class="container principles-grid"><div><p class="eyebrow">Communication principles</p><h2>What you can expect from every conversation.</h2></div><ul class="principle-list"><li><span class="principle-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h16M13 5l7 7-7 7"/></svg></span><div><h3>Plain language</h3><p>No unexplained jargon — if a term matters, we define it.</p></div></li><li><span class="principle-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 4v16M4 12h16"/></svg></span><div><h3>Realistic expectations</h3><p>We describe what preparation involves, not guaranteed results.</p></div></li><li><span class="principle-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8"/></svg></span><div><h3>Confidential by default</h3><p>Your circumstances are discussed only with your consultant.</p></div></li></ul></div></section>

<section class="section credentials-note"><div class="container"><div class="verify-callout"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 8v5M12 16h.01"/></svg><div><p class="eyebrow">Team &amp; credentials</p><p>Named consultant profiles and professional credentials will be published here once confirmed by the business — this section is a placeholder for verified detail, not a claim of current staffing.</p></div></div></div></section>

<section class="section quiet-next"><div class="container quiet-next-row"><p>Ready to talk through your plan?</p><div class="quiet-next-links"><a class="text-action" href="/consultation">Request a consultation <span aria-hidden="true">→</span></a><a class="text-action" href="/contact">Or get in touch <span aria-hidden="true">→</span></a></div></div></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>
