<?php
declare(strict_types=1); require __DIR__ . '/config.php'; $services = require __DIR__ . '/data/services.php'; $assistance = require __DIR__ . '/data/assistance.php';
$pageTitle = 'Visa Hat | Personal Guidance For Your Next Global Move';
$metaDescription = 'Explore visa consultation support for work, study and travel plans.';
require __DIR__ . '/includes/header.php';
?>
<main id="main-content">
<section class="hero" id="top"><div class="container hero-grid">
  <div class="hero-copy"><p class="eyebrow">Visa &amp; immigration consultation</p><h1>Personal Guidance For Your <strong>Next Global Move</strong></h1><p class="hero-text">Understand your next practical step with friendly consultation support for work, study, travel and immigration plans.</p><div class="button-row"><a class="btn btn-primary" href="/consultation">Request a consultation</a><a class="btn btn-outline" href="/contact">Contact us</a></div></div>
  <div class="hero-art"><img src="/assets/images/hero-consultation.svg" width="640" height="430" alt="Family discussing travel plans at an immigration consultation desk" fetchpriority="high"></div>
</div><div class="hero-wave" aria-hidden="true"><svg viewBox="0 0 1440 150" preserveAspectRatio="none"><path d="M0 52C185 12 296 166 507 118S776 31 965 72s313 52 475-20v98H0Z"/></svg></div></section>

<section class="services section" id="services"><div class="container"><header class="section-heading"><p class="eyebrow centered">Our categories</p><h2>Visa Immigration <strong>Consultation Services</strong></h2><p>A quick look at the visa categories we cover — see the visa page for the full picture.</p></header><div class="service-grid service-grid--compact">
<?php foreach ($services as $slug => $service): ?><article class="service-card service-card--<?= e($service['icon']) ?> service-card--compact"><div class="service-icon" aria-hidden="true"><svg viewBox="0 0 48 48"><use href="/assets/images/service-icons.svg#<?= e($service['icon']) ?>"></use></svg></div><div class="service-content"><h3><?= e($service['title']) ?></h3><a href="<?= e(service_url($slug)) ?>">View category <span aria-hidden="true">→</span></a></div></article><?php endforeach; ?>
</div><p class="centered section-link"><a class="text-action" href="/visa">See all visa categories <span aria-hidden="true">→</span></a></p></div></section>

<section class="section identity-band" id="about"><div class="container identity-band-inner"><div class="identity-copy"><p class="eyebrow">Who is Visa Hat?</p><h2>An independent consultation service for people planning a move abroad.</h2><p>We help you organise your questions and understand preparation — for work, study, visiting, or a temporary opportunity — before you commit to a path. We are not a law firm, and we do not submit applications on your behalf.</p><a class="text-action" href="/about">Read more about our approach <span aria-hidden="true">→</span></a></div><ul class="identity-badges"><li>Personal consultation</li><li>Plain-language guidance</li><li>No outcome guarantees</li></ul></div></section>

<section class="section assist-section"><div class="container"><header class="section-heading left-heading"><p class="eyebrow">What we help with</p><h2>Four ways we support your preparation.</h2></header><div class="assist-row"><?php foreach ($assistance as $slug => $item): ?><a class="assist-tile" href="/services#<?= e($slug) ?>"><span class="assist-icon" aria-hidden="true"><svg viewBox="0 0 48 48"><use href="/assets/images/service-icons.svg#<?= e($item['icon']) ?>"></use></svg></span><b><?= e($item['title']) ?></b><span class="assist-arrow" aria-hidden="true">→</span></a><?php endforeach; ?></div><p class="centered section-link"><a class="text-action" href="/services">See what each service includes <span aria-hidden="true">→</span></a></p></div></section>

<section class="section benefit-start-section"><div class="container benefit-start-grid"><div><p class="eyebrow">Who benefits</p><h2>Wherever your plan is headed, start here.</h2><ul class="benefit-list"><li>Skilled workers exploring an overseas role</li><li>Visitors planning a short trip abroad</li><li>Temporary workers preparing for a placement</li><li>Students planning an overseas study move</li></ul></div><div class="start-steps"><p class="eyebrow">How to get started</p><ol class="mini-steps mini-steps--home"><li>Choose the topic closest to your plan</li><li>Gather your destination, timeline, and questions</li><li>Request a consultation</li></ol><a class="btn btn-primary" href="/consultation">Request a consultation</a></div></div></section>

<section class="section directory-section"><div class="container"><header class="section-heading left-heading"><p class="eyebrow">Find out more</p><h2>Where to look for deeper detail.</h2></header><div class="directory-grid"><a href="/about"><b>About</b><span>Who we are, and how a consultation works.</span></a><a href="/services"><b>Services</b><span>What's included in each type of support.</span></a><a href="/visa"><b>Visa categories</b><span>Work, study, visit, and temporary-work guidance.</span></a><a href="/contact"><b>Contact</b><span>General enquiries and how to reach us.</span></a></div></div></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>