<?php declare(strict_types=1); require __DIR__ . '/config.php'; $services = require __DIR__ . '/data/services.php'; $pageTitle = 'Visa Categories | Visa Hat'; $metaDescription = 'Explore the visa categories Visa Hat covers: skilled worker, visitor, temporary work, and student.'; require __DIR__ . '/includes/header.php'; ?>
<main id="main-content">
<section class="section" style="padding:44px 0 0"><div class="container destinations-invite"><div><h2>Planning around a specific country?</h2><p>Browse our destination directory — 39 countries and visa areas, searchable and filterable by region.</p></div><a class="btn btn-primary" href="/visa/destinations">Explore Visa Destinations</a></div></section>

<section class="page-hero"><div class="container"><p class="eyebrow">Visa categories</p><h1>Four starting points for your <strong>global move.</strong></h1><p>Each category below covers a different kind of plan. Open the one closest to yours for an overview and a preparation checklist.</p></div></section>

<section class="section"><div class="container"><div class="service-grid"><?php foreach ($services as $slug => $service): ?><article class="service-card service-card--<?= e($service['icon']) ?>"><div class="service-icon" aria-hidden="true"><svg viewBox="0 0 48 48"><use href="/assets/images/service-icons.svg#<?= e($service['icon']) ?>"></use></svg></div><div class="service-content"><p class="card-label">Visa category</p><h2><?= e($service['title']) ?></h2><p><?= e($service['summary']) ?></p><a href="<?= e(service_url($slug)) ?>">Explore this category <span aria-hidden="true">→</span></a></div><i class="card-dots" aria-hidden="true"></i></article><?php endforeach; ?></div></div></section>

<section class="section choice-section"><div class="container choice-panel"><div><p class="eyebrow">Still deciding?</p><h2>Begin with the purpose of your move.</h2><p>If your plan is still taking shape, you do not need a perfect label yet. Start with whether you are exploring work, study, a visit, or a temporary opportunity, and refine it from there.</p></div><div class="choice-links"><a href="/visa/skilled-worker"><span>Work</span><b>Skilled worker guidance</b><i aria-hidden="true">→</i></a><a href="/visa/student"><span>Study</span><b>Student visa guidance</b><i aria-hidden="true">→</i></a><a href="/visa/visitor"><span>Visit</span><b>Visitor visa guidance</b><i aria-hidden="true">→</i></a><a href="/visa/temporary-work"><span>Temporary</span><b>Temporary work guidance</b><i aria-hidden="true">→</i></a></div></div></section>

<section class="section"><div class="container two-column"><div><p class="eyebrow">Looking for consultancy details?</p><h2>Visa categories vs. our services.</h2></div><div><p>This page is about the visa categories themselves — what each one generally covers. For details on how a Visa Hat consultation actually works, including what's included and what to prepare, see our services page.</p><a class="text-action" href="/services">See what our consultations include <span aria-hidden="true">→</span></a></div></div></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>
